name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run tests
        run: go test ./internal/test -v -coverprofile=coverage.out ./...

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            coveralls-token: ${{ secrets.COVERALLS_TOKEN }}
            path-to-lcov: coverage.out

